[env:teensy_static_fire]
platform = teensy
board = teensy41
framework = arduino
lib_deps = https://github.com/PaulStoffregen/RadioHead.git
lib_ignore = RadioHead@1.120.0
build_src_filter = +<static_fire.cpp> -<radio_test_tx.cpp> -<radio_test_rx.cpp>

[env:teensy_radio_tx]
platform = teensy
board = teensy41
framework = arduino
lib_deps = https://github.com/PaulStoffregen/RadioHead.git
lib_ignore = RadioHead@1.120.0
build_src_filter = +<radio_test_tx.cpp> -<static_fire.cpp> -<radio_test_rx.cpp>


[env:feather_radio_rx]
platform = atmelsam
board = adafruit_feather_m0
framework = arduino
lib_deps = https://github.com/PaulStoffregen/RadioHead.git
build_src_filter = +<feather_radio_rx.cpp> -<static_fire.cpp> -<radio_test_tx.cpp>