[teensy_base]
platform = teensy
board = teensy41
framework = arduino
build_flags = -O2
monitor_speed = 115200
monitor_echo = yes
monitor_filters = send_on_enter
monitor_eol = LF

[env:ident]
extends = teensy_base
build_src_filter = +<tvc_servo_ident.cpp>

[env:staticfire]
extends = teensy_base
build_src_filter = +<static_fire.cpp>
lib_deps = greiman/SdFat@^2.2.2