#!/usr/bin/env python3
"""Generate core/params.h and sim/tvc_params.py from params.yaml. See SPEC.md Section 2."""
import argparse
import hashlib
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent


def format_cpp_float(value):
    return f"{value!r}f"


def emit_cpp_leaf(name, value, dotted_path, measure_list, indent):
    pad = "    " * indent
    if isinstance(value, str) and value == "MEASURE":
        measure_list.append(dotted_path)
        return f"{pad}constexpr float {name} = NAN;\n"
    if isinstance(value, bool):
        return f"{pad}constexpr bool {name} = {'true' if value else 'false'};\n"
    if isinstance(value, int):
        return f"{pad}constexpr int {name} = {value};\n"
    if isinstance(value, float):
        return f"{pad}constexpr float {name} = {format_cpp_float(value)};\n"
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'{pad}constexpr const char* {name} = "{escaped}";\n'
    if isinstance(value, list):
        if all(isinstance(v, bool) for v in value):
            raise TypeError(f"{dotted_path}: bool arrays not supported")
        if all(isinstance(v, int) for v in value):
            body = ", ".join(str(v) for v in value)
            return f"{pad}constexpr int {name}[{len(value)}] = {{{body}}};\n"
        if all(isinstance(v, (int, float)) for v in value):
            body = ", ".join(format_cpp_float(float(v)) for v in value)
            return f"{pad}constexpr float {name}[{len(value)}] = {{{body}}};\n"
        raise TypeError(f"{dotted_path}: unsupported list element types")
    raise TypeError(f"{dotted_path}: unsupported type {type(value).__name__}")


def emit_cpp_namespace(name, mapping, dotted_prefix, measure_list, indent):
    pad = "    " * indent
    lines = [f"{pad}namespace {name} {{\n"]
    for key, value in mapping.items():
        dotted = f"{dotted_prefix}.{key}" if dotted_prefix else key
        if isinstance(value, dict):
            lines.append(emit_cpp_namespace(key, value, dotted, measure_list, indent + 1))
        else:
            lines.append(emit_cpp_leaf(key, value, dotted, measure_list, indent + 1))
    lines.append(f"{pad}}}  // namespace {name}\n")
    return "".join(lines)


def generate_cpp(data, params_hash):
    measure_list = []
    body = ["namespace tvc {\nnamespace params {\n\n"]
    body.append(f'constexpr const char* kParamsHash = "{params_hash}";\n\n')
    for key, value in data.items():
        if key == "sim_overrides":
            # Paper-simulation stand-ins for un-MEASUREd hardware fields, not measured
            # values. Firmware must never see these; sim/tvc_params.py gets them below.
            continue
        if isinstance(value, dict):
            body.append(emit_cpp_namespace(key, value, key, measure_list, 1))
        else:
            body.append(emit_cpp_leaf(key, value, key, measure_list, 1))
        body.append("\n")
    entries = ", ".join(f'"{m}"' for m in measure_list)
    body.append(f"constexpr const char* kMeasureList[] = {{{entries}}};\n")
    body.append(f"constexpr int kMeasureCount = {len(measure_list)};\n\n")
    body.append("}  // namespace params\n}  // namespace tvc\n")
    header = (
        "// GENERATED by tools/gen_params.py from params.yaml. Do not edit by hand.\n"
        "// See SPEC.md Section 2.\n"
        "#pragma once\n\n"
        "#include <cmath>\n\n"
    )
    return header + "".join(body)


def to_py_ns_repr(value, dotted_path, measure_list):
    if isinstance(value, dict):
        items = ", ".join(
            f"{key}={to_py_ns_repr(v, f'{dotted_path}.{key}' if dotted_path else key, measure_list)}"
            for key, v in value.items()
        )
        return f"SimpleNamespace({items})"
    if isinstance(value, str) and value == "MEASURE":
        measure_list.append(dotted_path)
        return "float('nan')"
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, (int, float, str)):
        return repr(value)
    if isinstance(value, list):
        return "[" + ", ".join(to_py_ns_repr(v, dotted_path, measure_list) for v in value) + "]"
    raise TypeError(f"{dotted_path}: unsupported type {type(value).__name__}")


def generate_python(data, params_hash):
    measure_list = []
    lines = [
        '"""GENERATED by tools/gen_params.py from params.yaml. Do not edit by hand.',
        "See SPEC.md Section 2.",
        '"""',
        "from types import SimpleNamespace",
        "",
        f'PARAMS_HASH = "{params_hash}"',
        "",
    ]
    for key, value in data.items():
        lines.append(f"{key} = {to_py_ns_repr(value, key, measure_list)}")
    lines.append("")
    lines.append(f"MEASURE_LIST = {measure_list!r}")
    lines.append("")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--params", type=Path, default=REPO_ROOT / "params.yaml")
    parser.add_argument("--cpp-out", type=Path, default=REPO_ROOT / "core" / "params.h")
    parser.add_argument("--py-out", type=Path, default=REPO_ROOT / "sim" / "tvc_params.py")
    args = parser.parse_args()

    raw = args.params.read_bytes()
    params_hash = hashlib.sha256(raw).hexdigest()
    data = yaml.safe_load(raw)

    if data.get("schema") != 1:
        raise SystemExit(f"{args.params}: unsupported schema {data.get('schema')!r} (expected 1)")

    args.cpp_out.parent.mkdir(parents=True, exist_ok=True)
    args.py_out.parent.mkdir(parents=True, exist_ok=True)
    args.cpp_out.write_text(generate_cpp(data, params_hash))
    args.py_out.write_text(generate_python(data, params_hash))

    print(
        f"generated {args.cpp_out.relative_to(REPO_ROOT)} and "
        f"{args.py_out.relative_to(REPO_ROOT)} from {args.params.name} (hash {params_hash[:12]})"
    )


if __name__ == "__main__":
    main()
