#!/usr/bin/env python3
"""Prove core/ produces identical outputs from Python (ctypes) and from the firmware's own
native unit test. See SPEC.md Section 6.1.

Generates a fixed 3 s / 150 Hz trace of (gyro, accel_tilt, gate) plus a set of fixture control
params (not the params.yaml flight values, most of which are still MEASURE), writes them once
into a C++ header included by firmware/test/test_parity, then runs the SAME trace through:
  (a) libtvccore.so/.dylib via ctypes
  (b) `pio test -e native -f test_parity`, which prints controller_step's outputs as CSV
and asserts the x_hat and u_cmd sequences are bitwise equal.

The fixture header is gitignored, not committed: firmware/pio_pregen.py regenerates it (via
--fixture-only, below) before every `pio test`, and this script regenerates it again before
every parity run, so it is always fresh and never shows up as a diff after a Mac run.
"""
import argparse
import ctypes
import math
import platform
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CORE_DIR = REPO_ROOT / "core"
FIRMWARE_DIR = REPO_ROOT / "firmware"
FIXTURE_PATH = FIRMWARE_DIR / "test" / "test_parity" / "parity_fixture.h"
PIO = Path.home() / ".platformio" / "penv" / "bin" / "pio"

TRACE_LEN = 450  # 3 s @ 150 Hz
DT = 1.0 / 150.0

# Fixture-only control params: fast/obvious behavior for a determinism check, not the
# params.yaml flight values (kp, kd, q, r there are still MEASURE).
FIXTURE_PARAMS = {
    "dt": DT,
    "kp": 4.0,
    "ki": 0.0,
    "kd": 0.5,
    "integral_clamp": 5.0,
    "max_deflection": 10.0,
    "q": 0.02,
    "r": 0.4,
    "slew_deg_per_s": 500.0,
}


def generate_trace():
    gyro, accel_tilt, gate = [], [], []
    for i in range(TRACE_LEN):
        t = i * DT
        gyro.append(30.0 * math.sin(2.0 * math.pi * 0.5 * t))
        accel_tilt.append(5.0 * math.cos(2.0 * math.pi * 0.3 * t))
        gate.append((i % 37) != 0)  # deterministic, occasional accel-gate dropout
    return gyro, accel_tilt, gate


def f32(value):
    return f"{value!r}f"


def write_fixture_header(path, gyro, accel_tilt, gate, params):
    n = len(gyro)
    gyro_lit = ", ".join(f32(v) for v in gyro)
    accel_lit = ", ".join(f32(v) for v in accel_tilt)
    gate_lit = ", ".join("true" if g else "false" for g in gate)
    lines = [
        "// GENERATED by tools/parity_test.py. Do not edit by hand.",
        "// Fixed 3 s / 150 Hz trace + fixture control params for the core/ parity check.",
        "// See SPEC.md Section 6.1. These are NOT the flight params.yaml values.",
        "#pragma once",
        "",
        f"constexpr int kParityTraceLen = {n};",
        f"constexpr float kParityGyroDegS[{n}] = {{{gyro_lit}}};",
        f"constexpr float kParityAccelTiltDeg[{n}] = {{{accel_lit}}};",
        f"constexpr bool kParityGate[{n}] = {{{gate_lit}}};",
        "",
        f"constexpr float kParityDt = {f32(params['dt'])};",
        f"constexpr float kParityKp = {f32(params['kp'])};",
        f"constexpr float kParityKi = {f32(params['ki'])};",
        f"constexpr float kParityKd = {f32(params['kd'])};",
        f"constexpr float kParityIntegralClamp = {f32(params['integral_clamp'])};",
        f"constexpr float kParityMaxDeflection = {f32(params['max_deflection'])};",
        f"constexpr float kParityQ = {f32(params['q'])};",
        f"constexpr float kParityR = {f32(params['r'])};",
        f"constexpr float kParitySlewDegPerS = {f32(params['slew_deg_per_s'])};",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")


def native_lib_path():
    name = "libtvccore.dylib" if platform.system() == "Darwin" else "libtvccore.so"
    return CORE_DIR / name


def run_ctypes_side(gyro, accel_tilt, gate, params):
    subprocess.run(["make", "-C", str(CORE_DIR), "native"], check=True)

    lib = ctypes.CDLL(str(native_lib_path()))
    c_float_p = ctypes.POINTER(ctypes.c_float)
    c_int_p = ctypes.POINTER(ctypes.c_int)
    lib.tvc_controller_step.argtypes = [
        c_float_p, c_float_p, c_float_p, c_float_p, c_float_p, c_int_p,
        ctypes.c_float, ctypes.c_float, ctypes.c_int,
        ctypes.c_float, ctypes.c_float, ctypes.c_float, ctypes.c_float,
        ctypes.c_float, ctypes.c_float, ctypes.c_float, ctypes.c_float, ctypes.c_float,
        c_float_p, c_float_p, c_float_p, c_float_p, c_float_p, c_int_p,
    ]
    lib.tvc_controller_step.restype = None

    x_hat = ctypes.c_float(0.0)
    P = ctypes.c_float(0.0)
    integral = ctypes.c_float(0.0)
    e_prev = ctypes.c_float(0.0)
    delta = ctypes.c_float(0.0)
    saturated = ctypes.c_int(0)
    out_x_hat = ctypes.c_float()
    out_u_raw = ctypes.c_float()
    out_u_cmd = ctypes.c_float()
    out_delta = ctypes.c_float()
    out_K = ctypes.c_float()
    out_accel_used = ctypes.c_int()

    results = []
    for i in range(len(gyro)):
        lib.tvc_controller_step(
            ctypes.byref(x_hat), ctypes.byref(P), ctypes.byref(integral),
            ctypes.byref(e_prev), ctypes.byref(delta), ctypes.byref(saturated),
            ctypes.c_float(gyro[i]), ctypes.c_float(accel_tilt[i]), int(gate[i]),
            ctypes.c_float(params["dt"]), ctypes.c_float(params["kp"]),
            ctypes.c_float(params["ki"]), ctypes.c_float(params["kd"]),
            ctypes.c_float(params["integral_clamp"]), ctypes.c_float(params["max_deflection"]),
            ctypes.c_float(params["q"]), ctypes.c_float(params["r"]),
            ctypes.c_float(params["slew_deg_per_s"]),
            ctypes.byref(out_x_hat), ctypes.byref(out_u_raw), ctypes.byref(out_u_cmd),
            ctypes.byref(out_delta), ctypes.byref(out_K), ctypes.byref(out_accel_used),
        )
        results.append((out_x_hat.value, out_u_cmd.value))
    return results


PARITY_LINE = re.compile(r"^PARITY,(\d+),(\S+),(\S+)\s*$")


def run_native_test_side():
    result = subprocess.run(
        [str(PIO), "test", "-e", "native", "-f", "test_parity", "-v"],
        cwd=str(FIRMWARE_DIR),
        capture_output=True,
        text=True,
    )
    output = result.stdout + result.stderr
    rows = {}
    for line in output.splitlines():
        m = PARITY_LINE.match(line.strip())
        if m:
            idx, x_hat, u_cmd = m.groups()
            rows[int(idx)] = (float.fromhex(x_hat), float.fromhex(u_cmd))
    if result.returncode != 0 or not rows:
        print(output)
        raise SystemExit(
            f"parity_test.py: `pio test -e native -f test_parity` failed or produced no "
            f"PARITY lines (exit {result.returncode})"
        )
    return [rows[i] for i in range(len(rows))]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--fixture-only",
        action="store_true",
        help="Only (re)write the gitignored parity fixture header, then exit. "
        "Used by firmware/pio_pregen.py so `pio test -e native` always has a fresh one.",
    )
    args = parser.parse_args()

    gyro, accel_tilt, gate = generate_trace()
    write_fixture_header(FIXTURE_PATH, gyro, accel_tilt, gate, FIXTURE_PARAMS)

    if args.fixture_only:
        print(f"parity_test.py: wrote {FIXTURE_PATH.relative_to(REPO_ROOT)}")
        return

    ctypes_results = run_ctypes_side(gyro, accel_tilt, gate, FIXTURE_PARAMS)
    native_results = run_native_test_side()

    if len(ctypes_results) != len(native_results):
        raise SystemExit(
            f"parity_test.py: length mismatch: ctypes={len(ctypes_results)} "
            f"native={len(native_results)}"
        )

    mismatches = [
        (i, cx, nx, cu, nu)
        for i, ((cx, cu), (nx, nu)) in enumerate(zip(ctypes_results, native_results))
        if cx != nx or cu != nu
    ]

    if mismatches:
        print(f"parity_test.py: FAIL, {len(mismatches)} / {len(ctypes_results)} steps mismatched")
        for i, cx, nx, cu, nu in mismatches[:10]:
            print(f"  step {i}: ctypes x_hat={cx!r} u_cmd={cu!r}  native x_hat={nx!r} u_cmd={nu!r}")
        sys.exit(1)

    print(f"parity_test.py: PASS, {len(ctypes_results)} steps bitwise-equal (x_hat, u_cmd)")


if __name__ == "__main__":
    main()
