// Emits a CSV trace of controller_step outputs for tools/parity_test.py to diff against the
// ctypes/libtvccore.so path. See SPEC.md Section 6.1. parity_fixture.h is generated by
// tools/parity_test.py (committed, regenerated on every run) from the same fixed 3 s / 150 Hz
// trace and fixture control params fed to the ctypes side, so both sides run identical inputs.
#include <unity.h>

#include <cstdio>

#include "controller.h"
#include "parity_fixture.h"

void setUp(void) {}
void tearDown(void) {}

void test_parity_trace_emits_csv(void) {
    tvc::AxisState state;
    tvc::ControlParams params{
        kParityDt,            kParityKp,           kParityKi,
        kParityKd,            kParityIntegralClamp, kParityMaxDeflection,
        kParityQAngle,        kParityQRate,        kParityR,           kParitySlewDegPerS,
    };

    for (int i = 0; i < kParityTraceLen; ++i) {
        tvc::AxisOut out = tvc::controller_step(state, kParityGyroDegS[i],
                                                 kParityAccelTiltDeg[i], kParityGate[i], params);
        // %a (hex float) is exact, unlike %g, which rounds to a decimal precision tuned
        // for round-tripping a float32, not the float64 tools/parity_test.py parses it as.
        std::printf("PARITY,%d,%a,%a\n", i, static_cast<double>(out.x_hat),
                    static_cast<double>(out.u_cmd));
    }

    TEST_ASSERT_TRUE(true);
}

int main(int argc, char **argv) {
    UNITY_BEGIN();
    RUN_TEST(test_parity_trace_emits_csv);
    return UNITY_END();
}
